version: '2'
services:

  development:
    build:
      context: .
      dockerfile: docker/Dev.dockerfile
    volumes:
      - ./lib:/package/lib
      - ./src:/package/src
      - ./tests:/package/tests
      - ./tests-src:/package/tests-src
      - ./.babelrc:/package/.babelrc
      - ./GRPCEventStore.proto:/package/GRPCEventStore.proto
      - ./package.json:/package/package.json

  test-node:
    build:
      context: .
      dockerfile: docker/Dev.dockerfile
    command: ["better-npm-run", "start:testnode"]
    volumes:
      - ./src:/package/src
      - ./tests-src:/package/tests-src
      - ./.babelrc:/package/.babelrc
      - ./GRPCEventStore.proto:/package/GRPCEventStore.proto
      - ./package.json:/package/package.json

  cockroach:
    image: cockroachdb/cockroach:beta-20170112
    ports:
      - "8080:8080"
      - "26257:26257"
    command: start --insecure
