version: '2'
services:

  development:
    build:
      context: .
      dockerfile: docker/Dev.dockerfile
    image: grpc-event-store:development
    volumes:
      - ./lib:/package/lib
      - ./src:/package/src
      - ./tests:/package/tests
      - ./lib-tests:/package/lib-tests
      - ./.babelrc:/package/.babelrc
      - ./GRPCEventStore.proto:/package/GRPCEventStore.proto
      - ./package.json:/package/package.json

  testServer:
    build:
      context: .
      dockerfile: docker/Dev.dockerfile
    image: grpc-event-store:development
    command: ["babel-node", "tests/testServer"]
    volumes:
      - ./lib:/package/lib
      - ./src:/package/src
      - ./tests:/package/tests
      - ./lib-tests:/package/lib-tests
      - ./.babelrc:/package/.babelrc
      - ./GRPCEventStore.proto:/package/GRPCEventStore.proto
      - ./package.json:/package/package.json

  cockroachdb:
    image: cockroachdb/cockroach:beta-20170406
    ports:
      - "8080:8080"
      - "26257:26257"
    command: start --insecure

  postgresql:
    image: postgres:9.6.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=eventstore
      - POSTGRES_PASSWORD=password
